# Generated by Django 2.2.4 on 2019-08-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(default='admin', max_length=255, verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
