# Generated by Django 2.2.4 on 2019-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='product_img/no-image-icon.png', upload_to='product_img/', verbose_name='상품이미지'),
        ),
    ]
